Models/ErrorViewModel.cs
namespace BaiThiTXT.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Process/StringProcess.cs
namespace BaiThiTXT.Models.Process;

    public class stringProcess
{

}

Models/TXTCau3.cs
using System.ComponentModel.DataAnnotations;

namespace BaiThiTXT.Models
{
    public class TXTCau3
    {
        [Key]
        [Display(Name ="Mã Lớp")]
        public int? MaLop {get;set;}
        [Display(Name ="Tên Lớp")]
        public string? TenLop {get;set;}
        [Display(Name ="Khóa Học")]
        public int? KhoaHoc {get;set;}
        
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using BaiThiTXT.Models;

namespace BaiThiTXT.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/TXTCau3Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BaiThiTXT.Models;

namespace BaiThiTXT.Controllers
{
    public class TXTCau3Controller : Controller
    {
        private readonly ApplicationDbContext _context;


        public TXTCau3Controller(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: TXTCau3
        public async Task<IActionResult> Index()
        {
              return _context.TXTCau3 != null ? 
                          View(await _context.TXTCau3.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.TXTCau3'  is null.");
        }

        // GET: TXTCau3/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.TXTCau3 == null)
            {
                return NotFound();
            }

            var tXTCau3 = await _context.TXTCau3
                .FirstOrDefaultAsync(m => m.MaLop == id);
            if (tXTCau3 == null)
            {
                return NotFound();
            }

            return View(tXTCau3);
        }

        // GET: TXTCau3/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TXTCau3/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaLop,TenLop,KhoaHoc")] TXTCau3 tXTCau3)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tXTCau3);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tXTCau3);
        }

        // GET: TXTCau3/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.TXTCau3 == null)
            {
                return NotFound();
            }

            var tXTCau3 = await _context.TXTCau3.FindAsync(id);
            if (tXTCau3 == null)
            {
                return NotFound();
            }
            return View(tXTCau3);
        }

        // POST: TXTCau3/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, [Bind("MaLop,TenLop,KhoaHoc")] TXTCau3 tXTCau3)
        {
            if (id != tXTCau3.MaLop)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tXTCau3);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TXTCau3Exists(tXTCau3.MaLop))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tXTCau3);
        }

        // GET: TXTCau3/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.TXTCau3 == null)
            {
                return NotFound();
            }

            var tXTCau3 = await _context.TXTCau3
                .FirstOrDefaultAsync(m => m.MaLop == id);
            if (tXTCau3 == null)
            {
                return NotFound();
            }

            return View(tXTCau3);
        }

        // POST: TXTCau3/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            if (_context.TXTCau3 == null)
            {
                return Problem("Entity set 'ApplicationDbContext.TXTCau3'  is null.");
            }
            var tXTCau3 = await _context.TXTCau3.FindAsync(id);
            if (tXTCau3 != null)
            {
                _context.TXTCau3.Remove(tXTCau3);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TXTCau3Exists(int? id)
        {
          return (_context.TXTCau3?.Any(e => e.MaLop == id)).GetValueOrDefault();
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BaiThiTXT</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BaiThiTXT.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BaiThiTXT</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TXTCau3" asp-action="Index">TXT Câu3</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BaiThiTXT - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/TXTCau3/Create.cshtml
@model BaiThiTXT.Models.TXTCau3

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>TXTCau3</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MaLop" class="control-label"></label>
                <input asp-for="MaLop" class="form-control" />
                <span asp-validation-for="MaLop" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TenLop" class="control-label"></label>
                <input asp-for="TenLop" class="form-control" />
                <span asp-validation-for="TenLop" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KhoaHoc" class="control-label"></label>
                <input asp-for="KhoaHoc" class="form-control" />
                <span asp-validation-for="KhoaHoc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/TXTCau3/Delete.cshtml
@model BaiThiTXT.Models.TXTCau3

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TXTCau3</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaLop)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaLop)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TenLop)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TenLop)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KhoaHoc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KhoaHoc)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MaLop" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/TXTCau3/Details.cshtml
@model BaiThiTXT.Models.TXTCau3

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>TXTCau3</h4>
    <hr />
    <dl class="row">
         <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaLop)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaLop)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TenLop)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TenLop)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KhoaHoc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KhoaHoc)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.MaLop">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/TXTCau3/Edit.cshtml
@model BaiThiTXT.Models.TXTCau3

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>TXTCau3</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MaLop" />
            <div class="form-group">
                <label asp-for="TenLop" class="control-label"></label>
                <input asp-for="TenLop" class="form-control" />
                <span asp-validation-for="TenLop" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KhoaHoc" class="control-label"></label>
                <input asp-for="KhoaHoc" class="form-control" />
                <span asp-validation-for="KhoaHoc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/TXTCau3/Index.cshtml
@model IEnumerable<BaiThiTXT.Models.TXTCau3>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
             <th>
                @Html.DisplayNameFor(model => model.MaLop)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TenLop)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.KhoaHoc)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
             <td>
                @Html.DisplayFor(modelItem => item.MaLop)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TenLop)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.KhoaHoc)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.MaLop">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.MaLop">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.MaLop">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>